"""Site copy. Edit here, then run `python3 build.py`.

Inline HTML is allowed in paragraph strings (links, <strong>, <em>).
British English throughout: modelling, programme, defence, recognised.
"""

SITE = {
    "name": "Element Digital Engineering",
    "former_name": "Filton Systems Engineering",
    "legal": "Filton Systems Engineering Ltd",
    "company_no": "08230492",
    "url": "https://filtonsys.com",
    "email": "global@filtonsys.com",
    "phone_display": "+44 (0)1454 527725",
    "phone_href": "+441454527725",
    "address_lines": ["Unit 13 Apex Court", "Woodlands", "Bristol", "BS32 4JT", "United Kingdom"],
    "maps_url": "https://www.openstreetmap.org/search?query=Apex%20Court%20Woodlands%20Bristol%20BS32%204JT",
    "tagline": "Fluid systems engineering, from concept to certification.",
    "description": (
        "Element Digital Engineering (formerly Filton Systems Engineering) designs, models, "
        "tests and certifies fuel, air, hydraulic, inerting and engine systems for aerospace, "
        "energy, water and nuclear customers worldwide."
    ),
}

# ---------------------------------------------------------------------------
# Capabilities. `slug` doubles as the URL under /what-we-do/ -- the first seven
# match the old site's URLs so existing links and search rankings carry over.
# ---------------------------------------------------------------------------
SERVICES = [
    {
        "slug": "fluid-modelling",
        "title": "Fluid modelling",
        "icon": "mesh",
        "summary": "One-dimensional network analysis through to full CFD, compressible and incompressible.",
        "lead": (
            "From one-dimensional network analysis to full computational fluid dynamics, we build "
            "models that answer the question at hand, and that stand up to certification scrutiny."
        ),
        "body": [
            "Element offers a wide range of modelling capability, from one-dimensional analysis to "
            "full computational fluid dynamics (CFD). Both compressible and incompressible flows can "
            "be assessed, with particular expertise in <a href=\"../surge-analysis/\">surge analysis "
            "and mitigation</a>.",
            "We choose the fidelity to fit the problem. System-level 1D models let us explore "
            "architectures, size lines and components and run large numbers of operating cases "
            "quickly. CFD then resolves the local detail where it matters: inside a valve, across a "
            "combustor, or at the free surface in a tank.",
        ],
        "lists": [
            ("Typical analyses", [
                "Combustor flows and heat transfer",
                "Fluid control devices",
                "Two-phase flow",
                "Stratification in fuel tanks",
                "Electrostatic charge and voltage levels",
                "Tank models to determine usable, unusable, unpumpable and undrainable fluid",
            ]),
        ],
        "related": ["surge-analysis", "electro-statics", "testing"],
    },
    {
        "slug": "surge-analysis",
        "title": "Surge analysis",
        "icon": "surge",
        "summary": "Predicting transient pressures that can reach several times normal operating pressure, and designing them out.",
        "lead": (
            "Transient pressures can reach several times a system's normal operating pressure. "
            "We predict them, and we design them out."
        ),
        "body": [
            "Surge pressures generated by rapid changes in fluid momentum are inherent within fluid "
            "systems. They can be caused by a wide range of mechanisms, such as valve closure, pump "
            "start and stop, and bubble collapse.",
            "These transient pressures can be several times greater than the normal operating "
            "pressure of the system. Left unchecked they can damage pipework, fittings and "
            "equipment, so identifying the threat early and mitigating it through design is "
            "essential.",
            "We model surge events across the operating envelope, correlate predictions with test "
            "data, and recommend practical mitigations that fit the wider system.",
        ],
        "lists": [
            ("What we deliver", [
                "Identification of surge mechanisms and critical cases",
                "Transient simulation of compressible and incompressible systems",
                "Peak pressure prediction to support structural sizing",
                "Mitigation design and trade studies",
                "Test correlation and model validation",
                "Analysis reports to support certification",
            ]),
        ],
        "related": ["fluid-modelling", "equipment-design", "testing"],
    },
    {
        "slug": "electro-statics",
        "title": "Electrostatics",
        "icon": "charge",
        "summary": "Analysing, quantifying and mitigating static charge in flammable, low-conductivity fluids.",
        "lead": (
            "Static charge in low-conductivity fuels is a recognised ignition hazard. We analyse "
            "it, quantify it and mitigate it."
        ),
        "body": [
            "The issue of static charge generation during the transfer and storage of flammable, "
            "low-conductivity fluids has long been recognised as a potential hazard. Charge is "
            "generated by friction between the fluid and system components such as pipes, filters "
            "and pumps, and can build up faster than it relaxes.",
            "Element has significant experience and proven capability in analysing, quantifying "
            "and mitigating this threat, from charge generation in pipe flow and filtration "
            "through to charge relaxation and voltage levels in tanks.",
        ],
        "lists": [
            ("What we deliver", [
                "Charge generation assessment for pipes, filters and components",
                "Charge relaxation and tank voltage prediction",
                "Design mitigation and trade studies",
                "Hazard assessment and certification evidence",
            ]),
        ],
        "related": ["fluid-modelling", "ice-and-water-in-fuel", "certification"],
    },
    {
        "slug": "ice-and-water-in-fuel",
        "title": "Ice and water in fuel",
        "icon": "ice",
        "summary": "Specialist understanding of how water and ice behave in fuel systems, and how to prove a design tolerates them.",
        "lead": (
            "Water is always present in aviation fuel. We make sure it never gets in the way of "
            "the engine."
        ),
        "body": [
            "Dissolved water comes out of solution as fuel cools and, at altitude, it can freeze. "
            "Ice can accrete in pipework, on screens and inside components, then release and "
            "block filters and fuel-metering equipment. It is one of the most demanding threats a "
            "fuel system must be shown to tolerate.",
            "Our engineers are specialists in the behaviour of water and ice in fuel. We help "
            "customers understand the threat to their system, design equipment and architectures "
            "that are robust to it, and plan and deliver the analysis and testing needed to "
            "demonstrate compliance with fuel system icing requirements.",
        ],
        "lists": [
            ("What we deliver", [
                "Water and ice threat assessment",
                "Ice accretion and release risk analysis",
                "Robust component and system design",
                "Icing test planning, rig definition and test control",
                "Certification strategy and compliance documentation",
            ]),
        ],
        "related": ["certification", "testing", "equipment-design"],
    },
    {
        "slug": "equipment-design",
        "title": "Equipment design",
        "icon": "valve",
        "summary": "Fluid mechanical equipment defined with its system-level impact in mind, from concept to manufacture.",
        "lead": "Fluid mechanical equipment, defined with the whole system in mind.",
        "body": [
            "Element defines fluid mechanical equipment while considering its system-level impact, "
            "so that a pump, valve or filter works not only on the bench but in the aircraft or "
            "plant it is destined for.",
            "We ensure the validation and verification of equipment against its requirements by "
            "specifying test programmes, assessing failures and proposing design improvements, "
            "taking a design from concept through to manufacture.",
        ],
        "lists": [
            ("What we deliver", [
                "Requirements capture and specification",
                "Concept and detailed mechanical design",
                "Prototyping",
                "Verification and validation planning",
                "Failure assessment and design improvement",
            ]),
        ],
        "related": ["testing", "certification", "skills"],
    },
    {
        "slug": "certification",
        "title": "Aircraft certification",
        "icon": "shield",
        "summary": "Documentation, evidence and strategy for challenging FAA and EASA requirements.",
        "lead": "Evidence, documentation and a clear strategy, agreed in step with the authorities.",
        "body": [
            "Element helps customers achieve product certification by delivering documentation and "
            "supporting evidence, in conjunction with direct consultation with the relevant "
            "authorities.",
            "Our personnel have been instrumental in defining and agreeing certification "
            "strategies for many challenging FAA and EASA requirements. Engaging early means the "
            "means of compliance, analysis and test plan are defined together, so certification "
            "is designed in rather than bolted on.",
        ],
        "lists": [
            ("What we deliver", [
                "Certification strategy and means of compliance",
                "Compliance documentation and substantiation reports",
                "Analysis and test evidence",
                "Similarity reports",
                "Consultation with FAA, EASA and other authorities",
            ]),
        ],
        "related": ["ice-and-water-in-fuel", "electro-statics", "skills"],
    },
    {
        "slug": "testing",
        "title": "Test programmes and test rigs",
        "icon": "gauge",
        "summary": "Every aspect of fluid systems and equipment test programmes, from requirements to final report.",
        "lead": (
            "From test requirements to the final report, we manage every aspect of fluid systems "
            "and equipment test programmes."
        ),
        "body": [
            "Element manages all aspects of fluid systems and equipment test programmes. We define "
            "product test requirements and the test rigs and tooling needed to meet them, act as "
            "test controller through prototype, qualification and robustness phases, and analyse "
            "data both in real time and after test completion.",
            "We have extensive knowledge of the aerospace environmental requirements set out in "
            "specifications such as RTCA DO-160 and MIL-STD-810, and design bespoke test rigs "
            "that replicate real-world operating conditions.",
        ],
        "lists": [
            ("What we deliver", [
                "Product test requirements",
                "Test rig and tooling requirements",
                "Test control during prototype, qualification and robustness phases",
                "Real-time and post-test data analysis",
                "Formal test data reports",
            ]),
        ],
        "standards": ["RTCA DO-160", "MIL-STD-810"],
        "related": ["equipment-design", "certification", "fluid-modelling"],
    },
    {
        "slug": "skills",
        "title": "Core skills",
        "icon": "doc",
        "summary": "The engineering disciplines and technical writing behind a complete project solution.",
        "lead": "The engineering disciplines behind a complete project solution.",
        "body": [
            "Our fluid systems and equipment experience is complemented by a wide range of "
            "engineering disciplines, used to support programmes and provide a complete project "
            "solution. We can assess an existing design, or take a fluid system or equipment "
            "package through the complete product development cycle.",
            "We pride ourselves on our technical writing: the documents that programmes and "
            "authorities depend on, written clearly and to a high standard.",
        ],
        "lists": [
            ("Disciplines", [
                "Systems engineering",
                "Mechanical design",
                "Stress analysis",
                "Safety and reliability",
                "Simulation and modelling",
                "Project management",
            ]),
            ("Technical documents we write", [
                "Similarity reports",
                "Test procedures",
                "Test reports",
                "Stress analysis reports",
                "Reliability reports",
                "Specifications",
            ]),
        ],
        "related": ["equipment-design", "certification", "testing"],
    },
]

SPECIALISMS = [
    ("ice-and-water-in-fuel", "Ice and water in fuel",
     "How water comes out of solution, freezes, accretes and releases, and how to prove a fuel system tolerates it."),
    ("electro-statics", "Electrostatics",
     "Charge generation and relaxation in low-conductivity fluids, quantified and designed out."),
    ("surge-analysis", "Surge analysis",
     "Transient pressures several times normal operating pressure, predicted and mitigated."),
]

LIFECYCLE = [
    ("Concept", "Architecture and requirements"),
    ("Design", "Systems and equipment"),
    ("Simulate", "1D to full CFD"),
    ("Prototype", "Build and prove"),
    ("Test", "Rigs and programmes"),
    ("Certify", "Evidence and documentation"),
]

SYSTEMS = ["Fuel", "Air", "Hydraulic", "Inerting", "Engine"]

INDUSTRIES = [
    ("plane", "Aerospace and defence",
     "Our origin. Fuel, air, hydraulic, inerting and engine systems for civil and military aircraft."),
    ("h2", "Hydrogen",
     "Gaseous and liquid hydrogen systems for zero-emission aviation.", "hydrogen/"),
    ("wind", "Renewable energy",
     "Fluid system design and analysis for energy generation and storage."),
    ("pipe", "Oil and gas",
     "Surge and transient analysis for pipelines and process plant."),
    ("drop", "Water",
     "Transient analysis of pumping systems and networks."),
    ("atom", "Nuclear",
     "Rigorous, documented fluid system analysis for safety-critical plant."),
]

STATS = [
    ("2012", "Founded in Bristol"),
    ("10–25", "Years' experience across many of our engineers"),
    ("EN 9100", "Certified quality management"),
    ("UK + US", "Engineering teams"),
]

TIMELINE = [
    ("2012", "Founded in Bristol",
     "Filton Systems Engineering is established by fuel system and fluid mechanical specialists "
     "from the aerospace industry."),
    ("2022", "Liquid hydrogen",
     "FSE and Fabrum support GKN Aerospace on liquid hydrogen fuel systems under the Innovate "
     "UK-funded Safe Flight project."),
    ("2023", "Joins Element",
     "FSE is acquired by Element Materials Technology, Element's 50th acquisition, strengthening "
     "its digital engineering and aerospace capability."),
    ("Today", "Element Digital Engineering",
     "Fluid systems engineering for customers across the globe, from teams in the UK and US."),
]

DIFFERENTIATORS = [
    ("Deep specialism",
     "Recognised expertise in ice and water in fuel, electrostatics and surge, the problems other "
     "teams hand on."),
    ("The whole lifecycle",
     "A single source for mechanical design, simulation, analysis, prototyping, technical writing "
     "and testing."),
    ("Certification in mind",
     "Analysis, test and documentation built to satisfy FAA and EASA from the outset."),
    ("Global backing",
     "A specialist team with the reach of Element's worldwide testing and engineering network."),
]

HYDROGEN = {
    "lead": "Aerospace fluid systems expertise, applied to the fuel of the future.",
    "body": [
        "Hydrogen is one of the most promising routes to zero-emission flight, and one of the most "
        "demanding fluids to engineer with. Stored as a cryogenic liquid at around −253&nbsp;°C, it "
        "raises challenges in thermal management, boil-off, two-phase flow and safety that sit "
        "squarely within our core skills.",
        "Our team has extensive expertise with both gaseous and liquid hydrogen. Our dedicated "
        "facility at Kemble, UK features a hydrogen liquefaction plant designed and constructed "
        "in-house, with equipment for liquid hydrogen conditioning, liquefaction and storage.",
    ],
    "capabilities": [
        "Gaseous and liquid hydrogen fuel system design",
        "Cryogenic fluid modelling and analysis",
        "Liquid hydrogen conditioning, liquefaction and storage",
        "Demonstrator and test rig design and build",
        "Test programme management",
        "Safety analysis and documentation",
    ],
    "project": {
        "label": "Project highlight",
        "title": "Safe Flight liquid hydrogen demonstrator",
        "body": (
            "Under the Innovate UK-funded Safe Flight project, FSE and Fabrum supported GKN "
            "Aerospace on liquid hydrogen fuel systems for aviation. A ground-based demonstrator "
            "of a 2.4&nbsp;kW liquid hydrogen system was jointly designed with GKN Aerospace and "
            "built by FSE."
        ),
        "facts": [("2.4 kW", "Liquid hydrogen system demonstrator"), ("−253 °C", "Liquid hydrogen storage temperature")],
    },
}

QUALITY = {
    "lead": (
        "Independently certified quality management and cyber security, so customers can trust "
        "our work and their data."
    ),
    "certs": [
        {
            "code": "EN 9100:2018",
            "title": "Aerospace quality management",
            "text": "Technically equivalent to AS9100D. The aerospace sector's quality management "
                    "standard, building on ISO 9001 with industry-specific requirements.",
        },
        {
            "code": "ISO 9001:2015",
            "title": "Quality management",
            "text": "The international standard for quality management systems.",
        },
        {
            "code": "Cyber Essentials Plus",
            "title": "Cyber security",
            "text": "The UK government-backed scheme, with an independent technical audit verifying "
                    "that our security controls are in place.",
        },
    ],
    "scope": (
        "Project management, design, production and testing of aerospace products and systems, "
        "and test equipment."
    ),
    # Same paths as the old site: copy the PDFs across so these keep working.
    "documents": [
        ("Quality management system certificate", "assets/QMS-Certificate_2023.pdf"),
        ("Certificate of registration FS 738719", "assets/FS-738719-052024.pdf"),
    ],
}
